name: Homework
description: Request for backend support
title: "[Homework] <title>"
body:


  - type: textarea
    attributes:
      label: Details
      description: |
        Links? References? Anything that will give you more context about this knowledge bite

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
